import { chromium } from '@playwright/test';
import { readFile, mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const base = 'http://127.0.0.1:8791';
const key=(await readFile('.secrets/admin-key.txt','utf8')).trim();
const browser=await chromium.launch({headless:true});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}), errors=[];
 page.on('pageerror',error=>errors.push(error.message));
 await page.goto(base);
 await page.getByLabel('Código de acesso').fill(key);
 await page.getByRole('button',{name:'Entrar',exact:true}).click();
 await page.locator('#dashboard').waitFor({state:'visible'});
 await page.getByRole('button',{name:'Novo projeto',exact:true}).click();
 await page.locator('#project-form [name=name]').fill('Teste local '+Date.now());
 await page.locator('#project-form [name=description]').fill('Validação local da interface, sem dados de outros projetos.');
 await page.getByRole('button',{name:'Criar projeto',exact:true}).click();
 await page.locator('#project-dialog').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'+ Criar agente',exact:true}).click();
 await page.locator('#agent-form [name=name]').fill('Coordenador local');
 await page.locator('#agent-form button[type=submit]').click();
 await page.locator('#agent-dialog').waitFor({state:'hidden'});
 await page.getByText('Coordenador local',{exact:true}).first().waitFor();
 await page.locator('#task-form [name=title]').fill('Analisar o backlog');
 await page.locator('#task-form [name=prompt]').fill('Indique três prioridades baseadas em evidências.');
 await page.getByRole('button',{name:'Adicionar ao backlog',exact:true}).click();
 await page.locator('.task-card h3').filter({hasText:'Analisar o backlog'}).waitFor();
 await page.reload();
 await page.locator('.task-card h3').filter({hasText:'Analisar o backlog'}).first().waitFor();
 assert.equal(await page.locator('body').evaluate(el=>el.scrollWidth>innerWidth),false);
 await mkdir('.secrets/screenshots',{recursive:true});
 await page.screenshot({path:'.secrets/screenshots/desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'Alternar tema'}).click();
 assert.equal(await page.locator('body').evaluate(el=>el.scrollWidth>innerWidth),false);
 await page.screenshot({path:'.secrets/screenshots/mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);
 console.log('Interface OK: login, projeto, agente, backlog, persistência após recarga, desktop e celular sem overflow ou erros JS.');
 await page.getByRole('button',{name:'Sair',exact:true}).click();
 await page.locator('#login-panel').waitFor({state:'visible'});
 console.log('Logout OK.');
}finally{await browser.close();}
