import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync, readdirSync } from 'node:fs';
import worker, { makeSession } from '../src/worker.js';
function setup(ai = {run: async () => ({response:'Plano baseado no contexto recebido.',usage:{prompt_tokens:42,completion_tokens:12}})}) {
  const db = new DatabaseSync(':memory:'); for(const file of readdirSync(new URL('../migrations/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())db.exec(readFileSync(new URL('../migrations/'+file,import.meta.url),'utf8'));
  const adapter = sql => {let params=[];return {bind(...args){params=args;return this;},async first(){return db.prepare(sql).get(...params)||null;},async all(){return {results:db.prepare(sql).all(...params)};},async run(){return db.prepare(sql).run(...params);}};};
  const env={DB:{prepare:adapter},ADMIN_KEY:'test-only-private-key-0123456789',AI:ai};
  const request = async (path,method='GET',data,authenticated=true,extra={}) => {
    const headers = {'Content-Type':'application/json',...extra};
    if(authenticated)headers.Cookie='saasagents_session='+await makeSession(env.ADMIN_KEY);
    return worker.fetch(new Request('https://saasagents.test/api'+path,{method,headers,body:data===undefined?undefined:JSON.stringify(data)}),env);
  };
  return {request,env,db};
}
async function fixture(s){const p=await (await s.request('/projects','POST',{name:'SaaS Agents'})).json();const a=await(await s.request('/agents','POST',{project_id:p.id,name:'Coordenador',role:'Planejar',instructions:'Use fatos.'})).json();return {p,a};}
async function task(s,p,a){return(await s.request('/tasks','POST',{project_id:p.id,agent_id:a.id,title:'Resumo',prompt:'Leia o contexto.'})).json();}
test('dados privados exigem login; origem externa não pode gravar',async()=>{const s=setup();assert.equal((await s.request('/state','GET',undefined,false)).status,401);assert.equal((await s.request('/projects','POST',{name:'X'},true,{Origin:'https://evil.test'})).status,403);});
test('login cria cookie protegido, rejeita chave incorreta e limita tentativas',async()=>{const s=setup();let response=await s.request('/login','POST',{key:s.env.ADMIN_KEY},false);assert.equal(response.status,200);assert.match(response.headers.get('Set-Cookie'),/HttpOnly; SameSite=Strict/);assert.match(response.headers.get('Set-Cookie'),/Secure/);for(let i=0;i<10;i++)assert.equal((await s.request('/login','POST',{key:'wrong'},false)).status,401);assert.equal((await s.request('/login','POST',{key:'wrong'},false)).status,429);});
test('sessão adulterada é rejeitada',async()=>{const s=setup();const r=await s.request('/state','GET',undefined,false,{Cookie:'saasagents_session=9999999999.forged.bad'});assert.equal(r.status,401);});
test('validação e vínculo de projeto impedem tarefa em agente de outro projeto',async()=>{const s=setup();const {p,a}=await fixture(s);const other=await(await s.request('/projects','POST',{name:'Outro'})).json();assert.equal((await s.request('/tasks','POST',{project_id:other.id,agent_id:a.id,title:'Teste',prompt:'Teste'})).status,400);assert.equal((await s.request('/projects','POST',{name:''})).status,400);assert.equal((await s.request('/projects','POST',{name:'a'.repeat(25000)})).status,413);});
test('execução conclui e registra uso; uma tarefa não roda duas vezes',async()=>{let calls=0;const s=setup({run:async()=>{calls++;return{response:'Resultado',usage:{prompt_tokens:9,completion_tokens:3}};}});const {p,a}=await fixture(s);const t=await task(s,p,a);const r=await(await s.request('/tasks/'+t.id+'/run','POST',{})).json();assert.equal(r.status,'done');assert.equal(r.input_tokens,9);assert.equal((await s.request('/tasks/'+t.id+'/run','POST',{})).status,409);assert.equal(calls,1);});
test('erro do modelo é persistido sem expor detalhe sensível',async()=>{const s=setup({run:async()=>{throw new Error('SECRET_INTERNAL');}});const {p,a}=await fixture(s);const t=await task(s,p,a);const r=await(await s.request('/tasks/'+t.id+'/run','POST',{})).json();assert.equal(r.status,'failed');assert.ok(!JSON.stringify(r).includes('SECRET_INTERNAL'));});
test('token de conector só envia snapshot: não lê painel, não executa tarefa e pode ser revogado',async()=>{const s=setup();const {p,a}=await fixture(s);const c=await(await s.request('/connectors','POST',{project_id:p.id,name:'Local'})).json();const headers={Authorization:'Bearer '+c.token};assert.equal((await s.request('/ingest','POST',{project:'saasagents',overview:'README: versão local',files_count:12},false,headers)).status,200);assert.equal((await s.request('/state','GET',undefined,false,headers)).status,401);const t=await task(s,p,a);assert.equal((await s.request('/tasks/'+t.id+'/run','POST',{},false,headers)).status,401);const state=await(await s.request('/state')).json();assert.equal(state.connectors[0].snapshot.project,'saasagents');assert.ok(!JSON.stringify(state).includes(c.token));assert.ok(!JSON.stringify(state).includes('token_hash'));await s.request('/connectors/'+c.id,'DELETE');assert.equal((await s.request('/ingest','POST',{project:'saasagents'},false,headers)).status,401);});
test('IA recebe o snapshot só do projeto da tarefa',async()=>{let content='';const s=setup({run:async(model,input)=>{content=JSON.stringify(input);return{response:'Ok'};}});const {p,a}=await fixture(s);const c=await(await s.request('/connectors','POST',{project_id:p.id,name:'Pasta'})).json();await s.request('/ingest','POST',{project:'saasagents',overview:'CONTEXTO_LOCAL'},false,{Authorization:'Bearer '+c.token});const other=await(await s.request('/projects','POST',{name:'Outro'})).json();const c2=await(await s.request('/connectors','POST',{project_id:other.id,name:'Outro'})).json();await s.request('/ingest','POST',{project:'other',overview:'NAO_PODE_APARECER'},false,{Authorization:'Bearer '+c2.token});const t=await task(s,p,a);await s.request('/tasks/'+t.id+'/run','POST',{});assert.match(content,/CONTEXTO_LOCAL/);assert.ok(!content.includes('NAO_PODE_APARECER'));});
test('um agente não executa tarefas simultâneas',async()=>{let release;const s=setup({run:()=>new Promise(resolve=>{release=()=>resolve({response:'Ok'});})});const {p,a}=await fixture(s);const t1=await task(s,p,a),t2=await task(s,p,a);const first=s.request('/tasks/'+t1.id+'/run','POST',{});while(!release)await new Promise(r=>setTimeout(r,1));const second=await s.request('/tasks/'+t2.id+'/run','POST',{});assert.equal(second.status,409);release();await first;});
test('tarefas presas são marcadas como interrompidas',async()=>{const s=setup();const {p,a}=await fixture(s);const t=await task(s,p,a);s.db.prepare("UPDATE tasks SET status='running', started_at='2020-01-01T00:00:00.000Z' WHERE id=?").run(t.id);const state=await(await s.request('/state')).json();assert.equal(state.tasks[0].status,'failed');});

test('objetivo do dono é editável e persiste no estado',async()=>{const s=setup();const {p}=await fixture(s);const edit=await s.request('/projects/'+p.id,'PATCH',{name:'Produto',description:'Resumo',objective:'Objetivo definido pelo dono'});assert.equal(edit.status,200);const state=await(await s.request('/state')).json();assert.equal(state.projects[0].objective,'Objetivo definido pelo dono');});
